### ISSUE TITLE
Error at the metadata creation level

### ISSUE THREAD

**Issue by jordancaraballo** [nasa-nccs-hpda/vhr-cloudmask#72]
When processing the following file `/explore/nobackup/projects/hls/EVHR/Amhara-MS/WV02_20100212_M1BS_10300100033A2600-toa.tif` using the following command:

```bash
for i in {0..64}; do sbatch --mem-per-cpu=10240 -G1 -c10 -q ilab -t05-00:00:00 -J clouds --wrap="singularity exec --env PYTHONPATH=\"/explore/nobackup/people/jacaraba/development/vhr-cloudmask:/explore/nobackup/people/jacaraba/development/tensorflow-caney\" --nv -B $NOBACKUP,/explore/nobackup/people,/explore/nobackup/projects /explore/nobackup/projects/ilab/containers/vhr-cloudmask.sif python /explore/nobackup/people/jacaraba/development/vhr-cloudmask/vhr_cloudmask/view/cloudmask_cnn_pipeline_cli.py -o '/explore/nobackup/projects/3sl/products/cloudmask/v2' -r '/explore/nobackup/projects/hls/EVHR/Amhara-MS/*-toa.tif' -s predict"; done
```

we get

```bash
2024-04-03 23:47:28; INFO; Prediction min=-10001, max=10000
Traceback (most recent call last):
  File "/explore/nobackup/people/jacaraba/development/vhr-cloudmask/vhr_cloudmask/view/cloudmask_cnn_pipeline_cli.py", line 133, in <module>
    sys.exit(main())
  File "/explore/nobackup/people/jacaraba/development/vhr-cloudmask/vhr_cloudmask/view/cloudmask_cnn_pipeline_cli.py", line 122, in main
    pipeline.predict()
  File "/explore/nobackup/people/jacaraba/development/vhr-cloudmask/vhr_cloudmask/model/pipelines/cloudmask_cnn_pipeline.py", line 329, in predict
    cloud_metadata = self.calc_metadata(prediction)
  File "/explore/nobackup/people/jacaraba/development/vhr-cloudmask/vhr_cloudmask/model/pipelines/cloudmask_cnn_pipeline.py", line 481, in calc_metadata
    metadata_dict['pct_cloudcover_total'] = self.calc_cloud_percentage(
  File "/explore/nobackup/people/jacaraba/development/vhr-cloudmask/vhr_cloudmask/model/pipelines/cloudmask_cnn_pipeline.py", line 503, in calc_cloud_percentage
    cloud_pixels = unique_dict[1]
KeyError: 1
```

**Comment by jordancaraballo** [comment]
The calculation of cloud percentage only catched one exception, and ignored the KeyError one. Adding the KeyError exception to the function:

```python
        # get cloudy pixels
        try:
            cloud_pixels = unique_dict[1]
        except (IndexError, KeyError):
            cloud_pixels = 0
```
