### ISSUE TITLE
Container has the old version of tensorflow caney. Need to fix that.

### ISSUE THREAD

**Issue by jordancaraballo** [nasa-nccs-hpda/vhr-cloudmask#75]
Container has the old version of tensorflow caney. Need to fix that.

```bash
[sstrong@gpu014 ilab_testing]$ singularity exec --nv -B $NOBACKUP,/explore/nobackup/people,/explore/nobackup/projects /explore/nobackup/projects/ilab/ilab_testing/il-tk/ilab-toolkit-sandbox-1.0.3 vhr-cloudmask-cli -o '/explore/nobackup/projects/ilab/ilab_testing/il-tk/vhr-output' -r '/explore/nobackup/projects/3sl/data/Tappan/Tappan16*_data.tif' '/explore/nobackup/projects/3sl/data/Tappan/Tappan15*_data.tif' -s predict
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (700) bind mounts
13:4: not a valid test operator: (
13:4: not a valid test operator: 555.42.06
2024-08-02 10:37:28.855242: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-02 10:37:31.660665: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Segmentation Models: using `tf.keras` framework.
Traceback (most recent call last):
  File "/usr/local/bin/vhr-cloudmask-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/vhr_cloudmask/view/cloudmask_cnn_pipeline_cli.py", line 77, in main
    pipeline = CloudMaskPipeline(
  File "/usr/local/lib/python3.8/dist-packages/vhr_cloudmask/model/pipelines/cloudmask_cnn_pipeline.py", line 68, in __init__
    self.logger = logger if logger is not None else self._set_logger()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_caney/model/pipelines/cnn_segmentation.py", line 132, in _set_logger
    os.path.join(self.conf.data_dir, log_filename))
AttributeError: 'CloudMaskPipeline' object has no attribute 'conf'
```

**Comment by jordancaraballo** [comment]
The multiarchitecture attempt was not allowing the containers to be created. This was fixed at the tensorflow caney level.
